spring:
  profiles:
    active: 
      - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dev
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-test
---
spring:
  profiles: dong
  application:
    name: microservicecloud-config-dong
# 请保存为UTF-8格式
